const SearchHotels = [
    {
        id: 1,
        title: 'Light bright airy stylish apt & safe peaceful stay',
        image: 'https://i.ibb.co/fFKrgvv/Conceptual-of-travel-and-vacation.jpg',
        image2: 'https://i.ibb.co/fNGK2ym/photo-409842.jpg',
        guests: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        facility: 'Wifi Air conditioning Kitchen',
        cancellation: 'Cancellation flexibility available',
        rating: 4.9,
        totalRating: 20,
        price: 34,
        shift: 'Night',
        totalPrice: 167,
        city: 'Dhaka',
        country: 'Bangladesh',
        EntireHome: 'You’ll have the condominium to yourself.',
        SelfCheckIn: 'You can check in with the doorman.',
        SparklingClean: '10 recent guests said this place was sparkling clean.',
        Superhost: "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
        description: "It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free. You’ll love my place for its lovely and bright looks comfortable stay. Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm.It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free.You’ll love my place for its lovely and bright looks comfortable stay. Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm."
    },
    {
        id: 2,
        title: 'Apartment in Lost Panorama',
        image: 'https://i.ibb.co/wKr2010/hotel-room-1447201-340.jpg',
        image2: 'https://i.ibb.co/271JQzK/photo-87223.jpg',
        guests: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        facility: 'Wifi Air conditioning Kitchen',
        cancellation: 'Cancellation flexibility available',
        rating: 4.9,
        totalRating: 10,
        price: 52,
        shift: 'Night',
        totalPrice: 167,
        city: 'Dhaka',
        country: 'Bangladesh',
        EntireHome: 'You’ll have the condominium to yourself.',
        SelfCheckIn: 'You can check in with the doorman.',
        SparklingClean: '10 recent guests said this place was sparkling clean.',
        Superhost: "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
        description: "It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free. You’ll love my place for its lovely and bright looks comfortable stay. Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm.It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free.You’ll love my place for its lovely and bright looks comfortable stay. Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm."
    },
    {
        id: 3,
        title: 'AR Lounge & Pool (r&r + b&b)',
        image: 'https://i.ibb.co/nwLYQzP/the-interior-of-the-3475656-340.jpg',
        image2: 'https://i.ibb.co/p2mJBcs/photo-323705.jpg',
        guests: 4,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        facility: 'Wifi Air conditioning Kitchen',
        cancellation: 'Cancellation flexibility available',
        rating: 4.9,
        totalRating: 25,
        price: 44,
        shift: 'Night',
        totalPrice: 167,
        city: 'Dhaka',
        country: 'Bangladesh',
        EntireHome: 'You’ll have the condominium to yourself.',
        SelfCheckIn: 'You can check in with the doorman.',
        SparklingClean: '10 recent guests said this place was sparkling clean.',
        Superhost: "Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.",
        description: "It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free. You’ll love my place for its lovely and bright looks comfortable stay. Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm.It’s newly constructed 7 storied building maintaining building code by a locally famous architect. Enough lights and natural air are playing here. The place (apartment) is calm and noise free.You’ll love my place for its lovely and bright looks comfortable stay. Bangladesh is a beauty with its six seasons and green. The people are hospitable and worm."
    }
]
export default SearchHotels;

